#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/randomaze/string/template_parser.y".
#

require 'racc/parser'


require 'strscan'


module Randomaze

  module String

    class TemplateParser < Racc::Parser

module_eval <<'..end lib/randomaze/string/template_parser.y modeval..id78c7d41657', 'lib/randomaze/string/template_parser.y', 102

def self.parse str
  new.parse(str)
end

def parse str
  raise Racc::ParseError if str.empty?
  @tokens = self.class.tokenize str
  result = do_parse
  arr = []
  tmp = result
  while tmp[1].kind_of? Array
    arr << tmp.first
    tmp = tmp[1]
  end
  arr << tmp.first

  arr
end

def meta_set str
  case str
  when '\w'
    # FIXME: \w is not generate multi byte character.
    ['a'..'z', 'A'..'Z', 0..9, '_']
  when '\d'
    [0..9]
  else
    raise Racc::ParseError, "not support meta character #{first}"
  end
end

def next_token
  @tokens.shift
end

def self.tokenize str
  tokens = []
  s = StringScanner.new str
  state = :default
  until s.eos? do
    case state
    when :default
      case
      when s.scan(/\\./)
        tokens.push([:META_SET, s[0]])
      when s.scan(/\./)
        tokens.push([:DOT, s[0]])
      when s.scan(/\[/)
        state = :set_expr
        tokens.push([:EXPR_START, '[' ])
        tokens.push([:SETS_START, '[' ])
      when s.scan(/\{/)
        state = :count_expr
        tokens.push([:COUNT_START, '{' ])
      when s.scan(%r![^\\\[\{\}\]]+!)
        tokens.push [:IDENT_WORD, s[0]]
      else
        char = s.getch
        tokens.push [char, char]
      end
    when :count_expr
      case
      when s.scan(/\}/)
        state = :default
        tokens.push([:COUNT_END, '}' ])
      when s.scan(/[0-9]+/)
        tokens.push([:NUMBER, s[0].to_i ])
      when s.scan(/,/)
        tokens.push([',', ','])
      else
        char = s.getch
        raise Racc::ParseError, "invalid char #{char}"
      end

    when :set_expr
      case
      when s.scan(/\\./)
        tokens.push([:META_SET, s[0]])
      when s.scan(/\]/)
        state = :default
        tokens.push([:SETS_END, ']' ])
      when s.scan(/([\w])-([\w])/)
        tokens.push([ :RANGE, [ s[1], s[2] ] ])

      when s.scan(/[0-9]+/)
        raise Racc::ParseError, "#{s[0]} is wrong" if s[0].size > 1
        tokens.push([:NUMCHAR, s[0].to_i ])
      when s.scan(/[a-zA-Z]/)
        tokens.push([:ALPHA, s[0] ])
      when s.scan(/-/)
        tokens.push(['-', s[0] ])
      else
        char = s.getch
        tokens.push [:IDENT, char]
      end
    else
      raise "must not happend!!"
    end
  end

  tokens
end

..end lib/randomaze/string/template_parser.y modeval..id78c7d41657

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 0, 18, :_reduce_none,
 2, 18, :_reduce_2,
 1, 19, :_reduce_none,
 1, 19, :_reduce_4,
 1, 19, :_reduce_5,
 2, 19, :_reduce_6,
 2, 19, :_reduce_7,
 3, 19, :_reduce_8,
 3, 21, :_reduce_9,
 3, 20, :_reduce_10,
 5, 20, :_reduce_11,
 0, 22, :_reduce_none,
 2, 22, :_reduce_13,
 1, 23, :_reduce_none,
 1, 23, :_reduce_15,
 1, 24, :_reduce_16,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 2, 25, :_reduce_none,
 1, 25, :_reduce_20,
 1, 26, :_reduce_none,
 1, 26, :_reduce_none ]

racc_reduce_n = 23

racc_shift_n = 35

racc_action_table = [
    23,     1,     2,     3,     4,    23,    29,    28,    16,    18,
    20,    22,    25,    16,    18,    20,    22,    25,     1,     2,
     3,     4,     7,    14,    10,    12,    27,     7,    30,     7,
    32,    33,    34 ]

racc_action_check = [
    10,     0,     0,     0,     0,    17,    14,    14,    10,    10,
    10,    10,    10,    17,    17,    17,    17,    17,     6,     6,
     6,     6,    11,     7,     4,     5,    12,     3,    15,     2,
    20,    28,    33 ]

racc_action_pointer = [
    -1,   nil,    21,    19,    18,    25,    16,    14,   nil,   nil,
    -4,    14,    26,   nil,    -4,    21,   nil,     1,   nil,   nil,
    16,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,   nil,
   nil,   nil,   nil,    22,   nil ]

racc_action_default = [
    -1,    -3,    -4,    -5,   -23,   -23,    -1,   -23,    -6,    -7,
   -12,   -23,   -23,    -2,   -23,   -23,   -16,   -12,   -17,   -14,
   -23,   -15,   -21,   -20,   -18,   -22,    -8,    35,   -23,   -10,
    -9,   -13,   -19,   -23,   -11 ]

racc_goto_table = [
     8,     9,     5,    15,    11,   nil,   nil,   nil,    13,    26,
    31 ]

racc_goto_check = [
     3,     3,     1,     5,     4,   nil,   nil,   nil,     1,     3,
     5 ]

racc_goto_pointer = [
   nil,     2,   nil,    -2,     0,    -7,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     6,   nil,   nil,   nil,    17,    19,    21,    24 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :IDENT_WORD => 2,
 :DOT => 3,
 :META_SET => 4,
 :EXPR_START => 5,
 :SETS_START => 6,
 :SETS_END => 7,
 :COUNT_START => 8,
 :NUMBER => 9,
 :COUNT_END => 10,
 "," => 11,
 :RANGE => 12,
 :IDENT => 13,
 :meta_set => 14,
 :ALPHA => 15,
 :NUMCHAR => 16 }

racc_use_result_var = true

racc_nt_base = 17

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'IDENT_WORD',
'DOT',
'META_SET',
'EXPR_START',
'SETS_START',
'SETS_END',
'COUNT_START',
'NUMBER',
'COUNT_END',
'","',
'RANGE',
'IDENT',
'meta_set',
'ALPHA',
'NUMCHAR',
'$start',
'exprs',
'expr',
'count_expr',
'sets_expr',
'sets',
'set',
'range',
'ident',
'alnum']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 8
  def _reduce_2( val, _values, result )
              result = val
   result
  end
.,.,

 # reduce 3 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 15
  def _reduce_4( val, _values, result )
              token = val.shift
              result = [ ['a'..'z', 'A'..'Z', 0..9, '_'], 1 ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 20
  def _reduce_5( val, _values, result )
              token = val.shift
              result = [ meta_set(token), 1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 25
  def _reduce_6( val, _values, result )
              token, count = val
              result = [ ['a'..'z', 'A'..'Z', 0..9, '_'], count ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 30
  def _reduce_7( val, _values, result )
              token, count = val
              result = [ meta_set(token), count ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 40
  def _reduce_8( val, _values, result )
              first = val.shift
              result = nil
              if first == '['
                result = val
              else
                result = first
              end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 51
  def _reduce_9( val, _values, result )
              array = []
              val[1].flatten.each do |range|
                next unless range
                array << range
              end

              result = array.uniq
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 56
  def _reduce_10( val, _values, result )
               result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 60
  def _reduce_11( val, _values, result )
               result = val[1]..val[3]
   result
  end
.,.,

 # reduce 12 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 66
  def _reduce_13( val, _values, result )
              result = val
   result
  end
.,.,

 # reduce 14 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 72
  def _reduce_15( val, _values, result )
              result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 82
  def _reduce_16( val, _values, result )
              first,last = val.first.to_a
              if first =~ /\d/ && last =~ /\d/
                first = first.to_i
                last  = last.to_i
              end
              result = first..last
   result
  end
.,.,

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 91
  def _reduce_20( val, _values, result )
              first = val.shift
              result = meta_set(first)
   result
  end
.,.,

 # reduce 21 omitted

 # reduce 22 omitted

 def _reduce_none( val, _values, result )
  result
 end

    end   # class TemplateParser

  end   # module String

end   # module Randomaze
