#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/randomaze/string/template_parser.y".
#

require 'racc/parser'


require 'strscan'
require 'set'


module Randomaze

  module String

    class TemplateParser < Racc::Parser

module_eval <<'..end lib/randomaze/string/template_parser.y modeval..idcddcec71ab', 'lib/randomaze/string/template_parser.y', 119

def self.parse str
  new.parse(str)
end

def parse str
  raise Racc::ParseError if str.empty?
  @tokens = self.class.tokenize str
  result = do_parse
  arr = []
  tmp = result
  while tmp[1].kind_of? Array
    arr << tmp.first
    tmp = tmp[1]
  end
  arr << tmp.first

  arr
end

def meta_set str
  case str
  when '\w'
    # FIXME: \w is not generate multi byte character.
    ['a'..'z', 'A'..'Z', 0..9, '_']
  when '\d'
    [0..9]
  else
    raise Racc::ParseError, "not support meta character #{first}"
  end
end

def next_token
  @tokens.shift
end

def self.tokenize str
  tokens = []
  s = StringScanner.new str
  state = :default
  until s.eos? do
    case state
    when :default
      case
      when s.scan(/\\[a-z]/)
        tokens.push([:META_SET, s[0]])
      when s.scan(/\./)
        tokens.push([:DOT, s[0]])
      when s.scan(/\?/)
        tokens.push([:QUESTION, s[0]])
      when s.scan(/\[/)
        state = :set_expr
        tokens.push([:EXPR_START, '[' ])
        tokens.push([:SETS_START, '[' ])
      when s.scan(/\(/)
        tokens.push([:SELECT_START, '(' ])
      when s.scan(/\)/)
        tokens.push([:SELECT_END, ')' ])
      when s.scan(/\|/)
        tokens.push(['|', '|' ])
      when s.scan(/\{/)
        state = :count_expr
        tokens.push([:COUNT_START, '{' ])
      when s.scan(%r![^\)|\\\[\{\}\]]+!)
        tokens.push [:IDENT_WORD, s[0]]
      when s.scan(%r!\\([\?\[\]\{\}\*\+\^\$\\\.\|\(\)])!)
        tokens.push [:IDENT_WORD, s[1]]
      else
        char = s.getch
        tokens.push [char, char]
      end
    when :count_expr
      case
      when s.scan(/\}/)
        state = :default
        tokens.push([:COUNT_END, '}' ])
      when s.scan(/[0-9]+/)
        tokens.push([:NUMBER, s[0].to_i ])
      when s.scan(/,/)
        tokens.push([',', ','])
      else
        char = s.getch
        raise Racc::ParseError, "invalid char #{char}"
      end

    when :set_expr
      case
      when s.scan(/\\[a-z]/)
        tokens.push([:META_SET, s[0]])
      when s.scan(/\]/)
        state = :default
        tokens.push([:SETS_END, ']' ])
      when s.scan(/([\w])-([\w])/)
        tokens.push([ :RANGE, [ s[1], s[2] ] ])

      when s.scan(/[0-9]+/)
        raise Racc::ParseError, "#{s[0]} is wrong" if s[0].size > 1
        tokens.push([:NUMCHAR, s[0].to_i ])
      when s.scan(/[a-zA-Z]/)
        tokens.push([:ALPHA, s[0] ])
      when s.scan(/-/)
        tokens.push(['-', s[0] ])
      else
        char = s.getch
        tokens.push [:IDENT, char]
      end
    else
      raise "must not happend!!"
    end
  end

  tokens
end

..end lib/randomaze/string/template_parser.y modeval..idcddcec71ab

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 0, 22, :_reduce_none,
 2, 22, :_reduce_2,
 1, 23, :_reduce_none,
 1, 23, :_reduce_4,
 3, 23, :_reduce_5,
 5, 23, :_reduce_6,
 1, 23, :_reduce_7,
 2, 23, :_reduce_8,
 2, 23, :_reduce_9,
 2, 23, :_reduce_10,
 3, 23, :_reduce_11,
 3, 24, :_reduce_12,
 3, 25, :_reduce_13,
 5, 25, :_reduce_14,
 1, 25, :_reduce_15,
 0, 26, :_reduce_none,
 2, 26, :_reduce_17,
 1, 27, :_reduce_none,
 1, 27, :_reduce_19,
 1, 28, :_reduce_20,
 1, 29, :_reduce_none,
 1, 29, :_reduce_none,
 2, 29, :_reduce_none,
 1, 29, :_reduce_24,
 1, 30, :_reduce_none,
 1, 30, :_reduce_none ]

racc_reduce_n = 27

racc_shift_n = 42

racc_action_table = [
    27,     3,     4,     5,    10,    27,     6,     7,    12,    23,
    25,    28,    30,    32,    23,    25,    28,    30,    32,     3,
     4,     5,    19,    20,     6,     7,     3,     4,     5,    33,
    34,     6,     7,     3,     4,     5,    10,    10,     6,     7,
    12,    12,    36,    18,    16,    17,     8,    38,    39,    40,
    41 ]

racc_action_check = [
    16,     5,     5,     5,     6,    24,     5,     5,     6,    16,
    16,    16,    16,    16,    24,    24,    24,    24,    24,     0,
     0,     0,    13,    13,     0,     0,     2,     2,     2,    18,
    18,     2,     2,    20,    20,    20,     4,    15,    20,    20,
     4,    15,    22,    10,     7,     8,     1,    28,    34,    35,
    39 ]

racc_action_pointer = [
    17,    46,    24,   nil,    25,    -1,    -7,    35,    45,   nil,
    31,   nil,   nil,    17,   nil,    26,    -7,   nil,    16,   nil,
    31,   nil,    32,   nil,    -2,   nil,   nil,   nil,    29,   nil,
   nil,   nil,   nil,   nil,    36,    44,   nil,   nil,   nil,    37,
   nil,   nil ]

racc_action_default = [
    -1,   -27,    -1,    -3,    -4,   -27,    -7,   -27,   -27,    -2,
   -27,    -9,   -15,   -27,   -10,    -8,   -16,    42,   -27,    -5,
   -27,   -11,   -27,   -20,   -16,   -21,   -18,   -24,   -27,   -19,
   -25,   -22,   -26,   -13,   -27,   -27,   -12,   -17,   -23,   -27,
    -6,   -14 ]

racc_goto_table = [
    13,    11,    22,    14,     1,    15,     9,   nil,   nil,   nil,
    37,   nil,    21,   nil,   nil,    35 ]

racc_goto_check = [
     2,     4,     5,     4,     1,     3,     1,   nil,   nil,   nil,
     5,   nil,     4,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     4,    -5,    -2,    -3,   -14,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     2,   nil,   nil,   nil,    24,    26,    29,    31 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :IDENT_WORD => 2,
 :DOT => 3,
 :SELECT_START => 4,
 :SELECT_END => 5,
 "|" => 6,
 :META_SET => 7,
 :EXPR_START => 8,
 :SETS_START => 9,
 :SETS_END => 10,
 :COUNT_START => 11,
 :NUMBER => 12,
 :COUNT_END => 13,
 "," => 14,
 :QUESTION => 15,
 :RANGE => 16,
 :IDENT => 17,
 :meta_set => 18,
 :ALPHA => 19,
 :NUMCHAR => 20 }

racc_use_result_var = true

racc_nt_base = 21

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'IDENT_WORD',
'DOT',
'SELECT_START',
'SELECT_END',
'"|"',
'META_SET',
'EXPR_START',
'SETS_START',
'SETS_END',
'COUNT_START',
'NUMBER',
'COUNT_END',
'","',
'QUESTION',
'RANGE',
'IDENT',
'meta_set',
'ALPHA',
'NUMCHAR',
'$start',
'exprs',
'expr',
'sets_expr',
'count_expr',
'sets',
'set',
'range',
'ident',
'alnum']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 8
  def _reduce_2( val, _values, result )
              result = val
   result
  end
.,.,

 # reduce 3 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 15
  def _reduce_4( val, _values, result )
              token = val.shift
              result = [ ['a'..'z', 'A'..'Z', 0..9, '_'], 1 ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 19
  def _reduce_5( val, _values, result )
              result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 23
  def _reduce_6( val, _values, result )
              result = Set.new([val[1], val[3]])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 28
  def _reduce_7( val, _values, result )
              token = val.shift
              result = [ meta_set(token), 1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 32
  def _reduce_8( val, _values, result )
              result = [ val[1], 1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 37
  def _reduce_9( val, _values, result )
              token, count = val
              result = [ ['a'..'z', 'A'..'Z', 0..9, '_'], count ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 42
  def _reduce_10( val, _values, result )
              token, count = val
              result = [ meta_set(token), count ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 52
  def _reduce_11( val, _values, result )
              first = val.shift
              result = nil
              if first == '['
                result = val
              else
                result = first
              end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 63
  def _reduce_12( val, _values, result )
              array = []
              val[1].flatten.each do |range|
                next unless range
                array << range
              end

              result = array.uniq
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 68
  def _reduce_13( val, _values, result )
               result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 72
  def _reduce_14( val, _values, result )
               result = val[1]..val[3]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 76
  def _reduce_15( val, _values, result )
               result = 0..1
   result
  end
.,.,

 # reduce 16 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 82
  def _reduce_17( val, _values, result )
              result = val
   result
  end
.,.,

 # reduce 18 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 88
  def _reduce_19( val, _values, result )
              result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 98
  def _reduce_20( val, _values, result )
              first,last = val.first.to_a
              if first =~ /\d/ && last =~ /\d/
                first = first.to_i
                last  = last.to_i
              end
              result = first..last
   result
  end
.,.,

 # reduce 21 omitted

 # reduce 22 omitted

 # reduce 23 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 107
  def _reduce_24( val, _values, result )
              first = val.shift
              result = meta_set(first)
   result
  end
.,.,

 # reduce 25 omitted

 # reduce 26 omitted

 def _reduce_none( val, _values, result )
  result
 end

    end   # class TemplateParser

  end   # module String

end   # module Randomaze
