#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/randomaze/string/template_parser.y".
#

require 'racc/parser'


require 'strscan'
require 'set'


module Randomaze

  module String

    class TemplateParser < Racc::Parser

module_eval <<'..end lib/randomaze/string/template_parser.y modeval..id725b685947', 'lib/randomaze/string/template_parser.y', 131

def self.parse str
  new.parse(str)
end

def parse str
  raise Racc::ParseError if str.empty?
  @tokens = self.class.tokenize str
  result = do_parse
  arr = []
  tmp = result
  while tmp[1].kind_of? Array
    arr << tmp.first
    tmp = tmp[1]
  end
  arr << tmp.first

  arr
end

def meta_set str
  case str
  when '\w'
    # FIXME: \w is not generate multi byte character.
    ['a'..'z', 'A'..'Z', 0..9, '_']
  when '\d'
    [0..9]
  else
    raise Racc::ParseError, "not support meta character #{first}"
  end
end

def next_token
  @tokens.shift
end

def self.tokenize str
  tokens = []
  s = StringScanner.new str
  state = :default
  until s.eos? do
    case state
    when :default
      case
      when s.scan(/\\[a-z]/)
        tokens.push([:META_SET, s[0]])
      when s.scan(/\./)
        tokens.push([:DOT, s[0]])
      when s.scan(/\?/)
        tokens.push([:QUESTION, s[0]])
      when s.scan(/\*(\?)?/)
        tokens.push([:ASTERISK, s[0]])
      when s.scan(/\+(\?)?/)
        tokens.push([:PLUS, s[0]])
      when s.scan(/\[/)
        state = :set_expr
        tokens.push([:EXPR_START, '[' ])
        tokens.push([:SETS_START, '[' ])
      when s.scan(/\(/)
        tokens.push([:SELECT_START, '(' ])
      when s.scan(/\)/)
        tokens.push([:SELECT_END, ')' ])
      when s.scan(/\|/)
        tokens.push(['|', '|' ])
      when s.scan(/\{/)
        state = :count_expr
        tokens.push([:COUNT_START, '{' ])
      when s.scan(%r![^\)|\\\[\{\}\]]+!)
        tokens.push [:IDENT_WORD, s[0]]
      when s.scan(%r!\\([\?\[\]\{\}\*\+\^\$\\\.\|\(\)])!)
        tokens.push [:IDENT_WORD, s[1]]
      else
        char = s.getch
        tokens.push [char, char]
      end
    when :count_expr
      case
      when s.scan(/\}/)
        state = :default
        tokens.push([:COUNT_END, '}' ])
      when s.scan(/[0-9]+/)
        tokens.push([:NUMBER, s[0].to_i ])
      when s.scan(/,/)
        tokens.push([',', ','])
      else
        char = s.getch
        raise Racc::ParseError, "invalid char #{char}"
      end

    when :set_expr
      case
      when s.scan(/\\[a-z]/)
        tokens.push([:META_SET, s[0]])
      when s.scan(/\]/)
        state = :default
        tokens.push([:SETS_END, ']' ])
      when s.scan(/([\w])-([\w])/)
        tokens.push([ :RANGE, [ s[1], s[2] ] ])

      when s.scan(/[0-9]+/)
        raise Racc::ParseError, "#{s[0]} is wrong" if s[0].size > 1
        tokens.push([:NUMCHAR, s[0].to_i ])
      when s.scan(/[a-zA-Z]/)
        tokens.push([:ALPHA, s[0] ])
      when s.scan(/-/)
        tokens.push(['-', s[0] ])
      else
        char = s.getch
        tokens.push [:IDENT, char]
      end
    else
      raise "must not happend!!"
    end
  end

  tokens
end

..end lib/randomaze/string/template_parser.y modeval..id725b685947

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 0, 24, :_reduce_none,
 2, 24, :_reduce_2,
 1, 25, :_reduce_none,
 1, 25, :_reduce_4,
 3, 25, :_reduce_5,
 5, 25, :_reduce_6,
 1, 25, :_reduce_7,
 2, 25, :_reduce_8,
 2, 25, :_reduce_9,
 2, 25, :_reduce_10,
 3, 25, :_reduce_11,
 3, 26, :_reduce_12,
 3, 27, :_reduce_13,
 4, 27, :_reduce_14,
 5, 27, :_reduce_15,
 1, 27, :_reduce_16,
 1, 27, :_reduce_17,
 1, 27, :_reduce_18,
 0, 28, :_reduce_none,
 2, 28, :_reduce_20,
 1, 29, :_reduce_none,
 1, 29, :_reduce_22,
 1, 30, :_reduce_23,
 1, 31, :_reduce_none,
 1, 31, :_reduce_none,
 2, 31, :_reduce_none,
 1, 31, :_reduce_27,
 1, 32, :_reduce_none,
 1, 32, :_reduce_none ]

racc_reduce_n = 30

racc_shift_n = 45

racc_action_table = [
    26,     1,     3,     5,     9,    26,     6,     7,    10,    11,
    13,    27,    29,    31,    33,    24,    27,    29,    31,    33,
    24,     1,     3,     5,     9,    38,     6,     7,    10,    11,
    13,     1,     3,     5,    21,    22,     6,     7,     1,     3,
     5,     9,    18,     6,     7,    10,    11,    13,    41,    42,
    35,    36,    19,     8,    40,    20,    43,    44 ]

racc_action_check = [
    18,     5,     5,     5,     3,    28,     5,     5,     3,     3,
     3,    18,    18,    18,    18,    18,    28,    28,    28,    28,
    28,     4,     4,     4,     6,    25,     4,     4,     6,     6,
     6,    22,    22,    22,    15,    15,    22,    22,     0,     0,
     0,    17,     7,     0,     0,    17,    17,    17,    36,    36,
    20,    20,     8,     2,    31,     9,    37,    41 ]

racc_action_pointer = [
    36,   nil,    53,    -7,    19,    -1,    13,    33,    52,    43,
   nil,   nil,   nil,   nil,   nil,    29,   nil,    30,    -7,   nil,
    37,   nil,    29,   nil,   nil,    15,   nil,   nil,    -2,   nil,
   nil,    34,   nil,   nil,   nil,   nil,    36,    51,   nil,   nil,
   nil,    44,   nil,   nil,   nil ]

racc_action_default = [
    -1,    -3,   -30,    -4,    -1,   -30,    -7,   -30,   -30,   -30,
   -16,   -17,    -9,   -18,    -2,   -30,   -10,    -8,   -19,    45,
   -30,    -5,   -30,   -11,   -29,   -30,   -27,   -23,   -19,   -24,
   -21,   -30,   -22,   -28,   -25,   -13,   -30,   -30,   -12,   -20,
   -26,   -30,   -14,    -6,   -15 ]

racc_goto_table = [
    15,    12,    25,     2,    16,    17,   nil,    14,   nil,   nil,
   nil,   nil,    39,   nil,   nil,    23,   nil,    37 ]

racc_goto_check = [
     2,     4,     5,     1,     4,     3,   nil,     1,   nil,   nil,
   nil,   nil,     5,   nil,   nil,     4,   nil,     2 ]

racc_goto_pointer = [
   nil,     3,    -5,    -2,    -2,   -16,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     4,   nil,   nil,   nil,    28,    30,    32,    34 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :IDENT_WORD => 2,
 :DOT => 3,
 :SELECT_START => 4,
 :SELECT_END => 5,
 "|" => 6,
 :META_SET => 7,
 :EXPR_START => 8,
 :SETS_START => 9,
 :SETS_END => 10,
 :COUNT_START => 11,
 :NUMBER => 12,
 :COUNT_END => 13,
 "," => 14,
 :QUESTION => 15,
 :ASTERISK => 16,
 :PLUS => 17,
 :RANGE => 18,
 :IDENT => 19,
 :meta_set => 20,
 :ALPHA => 21,
 :NUMCHAR => 22 }

racc_use_result_var = true

racc_nt_base = 23

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'IDENT_WORD',
'DOT',
'SELECT_START',
'SELECT_END',
'"|"',
'META_SET',
'EXPR_START',
'SETS_START',
'SETS_END',
'COUNT_START',
'NUMBER',
'COUNT_END',
'","',
'QUESTION',
'ASTERISK',
'PLUS',
'RANGE',
'IDENT',
'meta_set',
'ALPHA',
'NUMCHAR',
'$start',
'exprs',
'expr',
'sets_expr',
'count_expr',
'sets',
'set',
'range',
'ident',
'alnum']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 8
  def _reduce_2( val, _values, result )
              result = val
   result
  end
.,.,

 # reduce 3 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 15
  def _reduce_4( val, _values, result )
              token = val.shift
              result = [ ['a'..'z', 'A'..'Z', 0..9, '_'], 1 ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 19
  def _reduce_5( val, _values, result )
              result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 23
  def _reduce_6( val, _values, result )
              result = Set.new([val[1], val[3]])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 28
  def _reduce_7( val, _values, result )
              token = val.shift
              result = [ meta_set(token), 1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 32
  def _reduce_8( val, _values, result )
              result = [ val[1], 1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 37
  def _reduce_9( val, _values, result )
              token, count = val
              result = [ ['a'..'z', 'A'..'Z', 0..9, '_'], count ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 42
  def _reduce_10( val, _values, result )
              token, count = val
              result = [ meta_set(token), count ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 52
  def _reduce_11( val, _values, result )
              first = val.shift
              result = nil
              if first == '['
                result = val
              else
                result = first
              end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 63
  def _reduce_12( val, _values, result )
              array = []
              val[1].flatten.each do |range|
                next unless range
                array << range
              end

              result = array.uniq
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 68
  def _reduce_13( val, _values, result )
               result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 72
  def _reduce_14( val, _values, result )
               result = [ val[1], nil ]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 76
  def _reduce_15( val, _values, result )
               result = val[1]..val[3]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 80
  def _reduce_16( val, _values, result )
               result = 0..1
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 84
  def _reduce_17( val, _values, result )
               result = [0, nil]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 88
  def _reduce_18( val, _values, result )
               result = [1, nil]
   result
  end
.,.,

 # reduce 19 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 94
  def _reduce_20( val, _values, result )
              result = val
   result
  end
.,.,

 # reduce 21 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 100
  def _reduce_22( val, _values, result )
              result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 110
  def _reduce_23( val, _values, result )
              first,last = val.first.to_a
              if first =~ /\d/ && last =~ /\d/
                first = first.to_i
                last  = last.to_i
              end
              result = first..last
   result
  end
.,.,

 # reduce 24 omitted

 # reduce 25 omitted

 # reduce 26 omitted

module_eval <<'.,.,', 'lib/randomaze/string/template_parser.y', 119
  def _reduce_27( val, _values, result )
              first = val.shift
              result = meta_set(first)
   result
  end
.,.,

 # reduce 28 omitted

 # reduce 29 omitted

 def _reduce_none( val, _values, result )
  result
 end

    end   # class TemplateParser

  end   # module String

end   # module Randomaze
